version: "3.7"
    
services:
  mongo:
    image: mongo:5
    volumes:
      - db_data:/data/db
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: foo
      MONGO_INIT_DB_ROOT_PASSWORD: bar
    
  app:
    build:
      context: ./app
      dockerfile: dockerfiles/pureNode.development
    ports:
      - "3000:3000"
    environment:
      # In case the .aws folder doesn't have this set already
      AWS_REGION: us-east-1
      ENVIRONMENT: local
      LOG_LEVEL: debug
      DB_USER: foo
      DB_PASS: bar
      DB_HOST: mongo
      API_MODE: DEFAULT
      USE_REDIS: true
      REDIS_HOST: redis
      ENABLE_SSL: false
      SSL_KEY_PASSWORD: DO_NOT_USE_THIS
    volumes:
      # Enables live reload on code changes
      - "./app/src:/srv/src"
      # Allows the app to build the ui for us
      - "./app/bin:/srv/bin"
      # Keep the cert out of the build using volumes
      - "./app/certs/example.cert:/srv/server.cert"
      - "./app/certs/example.key:/srv/server.key"
      # enable aws access
      - ~/.aws:/root/.aws
    depends_on:
    #   - mongo
      - redis

  redis:
    image: redis

  devops:
    build:
      context: ./devops
    environment:
      # Move the history file to be in the volume
      - HISTFILE=/root/bash_history/.bash_history
    volumes:
      # Store the history
      - devops_history:/root/bash_history
      # Volume in the repo rather than copying it (saves time on start)
      - ./:/root/repo
      # Just in case we have any ssh to deal with
      - $HOME/.ssh:/root/.ssh
      # enable aws access
      - ~/.aws:/root/.aws

  nginx:
    build:
      context: ./app
      dockerfile: dockerfiles/nginx
    ports:
      - 8080:80

volumes:
  db_data:
  devops_history: