variable "aws_access_key" {
  type    = string
  default = ""
}

variable "aws_secret_key" {
  type    = string
  default = ""
}

# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/from-1.5/blocks/source
source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.aws_access_key}"
  ami_name      = "ubuntu-nodejs-18-${local.timestamp}"
  instance_type = "t3.medium"
  region        = "us-east-1"
  secret_key    = "${var.aws_secret_key}"
  source_ami_filter {
    filters = {
      name                = "ubuntu/images/*ubuntu-focal-20.04-amd64-server-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    # Owned by AWS
    owners      = ["099720109477"]
  }
  ssh_username = "ubuntu"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/from-1.5/blocks/build
build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    script = "./scripts/base-ubuntu.sh"
  }
  provisioner "shell" {
    script = "./scripts/nodejs-18-server.sh"
  }
  provisioner "file" {
    source = "/root/repo/devops/packer/scripts/cloudwatch-config.json"
    destination = "/home/ubuntu/cloudwatch-config.json"
  }
  provisioner "file" {
    source = "/root/repo/app"
    destination = "/home/ubuntu/app"
  }
  provisioner "shell" {
    script = "./scripts/setup-app.sh"
  }
}
